apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/digital-academy-devops/k8s-examples.git'
    path: apps
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
