apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akupriyanov-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/ANDRIKUP/devops_final_task.git
    targetRevision: main
    path: kubernetes/overlays
  destination:
    name: in-cluster
    namespace: akupriyanov-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true