apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amalkov-app
spec:
  project: default
  source:
    repoURL: https://github.com/Sodx1/sample-app
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: amalkov
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
