apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glebedev-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/I1ss/sample-app
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: glebedev-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true