apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mulenokv-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/mulenokivan/devops-final-task
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: mulenokv-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true