apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmironenko-app
spec:
  project: default
  source:
    repoURL: https://github.com/Stellarthoughts/devops-academy-final
    targetRevision: main
    path: deployment/overlay/common
  destination:
    name: in-cluster
    namespace: pmironenko
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
